from datetime import date

import pytest

from app.services.dob_parser import parse_dob_candidates

date_text = [
    {"text_str": "zero one zero five one nine five six", "date_val": date(1956, 1, 5)},
    {"text_str": "zero one two zero one nine five six", "date_val": date(1956, 1, 20)},
    {"text_str": "one zero two zero one nine five six", "date_val": date(1956, 10, 20)},
    {"text_str": "april twenty third nineteen sixty three", "date_val": date(1963, 4, 23)},
    {"text_str": "apr twenty three nineteen sixty three", "date_val": date(1963, 4, 23)},
    {"text_str": "one five nineteen fifty six", "date_val": date(1956, 1, 5)},
    {"text_str": "one five fifty six", "date_val": date(1956, 1, 5)},
    {"text_str": "one nineteen fifty six", "date_val": date(1956, 1, 19)},
    {"text_str": "twelve twenty two nineteen fifty six", "date_val": date(1956, 12, 22)},
    {"text_str": "twelve twenty two fifty six", "date_val": date(1956, 12, 22)},
    {"text_str": "twelve twenty fifty six", "date_val": date(1956, 12, 20)},
    {"text_str": "july twenty fifty six", "date_val": date(1956, 7, 20)},
    {"text_str": "july sixth fifty six", "date_val": date(1956, 7, 6)},
    {"text_str": "july twenty fifth fifty six", "date_val": date(1956, 7, 25)},
    {"text_str": "November eighteenth fifty six", "date_val": date(1956, 11, 18)},
    {"text_str": "December eleventh fifty six", "date_val": date(1956, 12, 11)},
    {"text_str": "December twelfth fifty six", "date_val": date(1956, 12, 12)},
    {"text_str": "December tenth fifty six", "date_val": date(1956, 12, 10)},
    {"text_str": "December nine fifty six", "date_val": date(1956, 12, 9)},
    {"text_str": "December ninth fifty six", "date_val": date(1956, 12, 9)},
    {"text_str": "December thirty first fifty six", "date_val": date(1956, 12, 31)},
    {"text_str": "December thirty one fifty six", "date_val": date(1956, 12, 31)},
    {"text_str": "December ten fifty six", "date_val": date(1956, 12, 10)},
    {"text_str": "November eighteen fifty six", "date_val": date(1956, 11, 18)},
    {"text_str": "December eleven fifty six", "date_val": date(1956, 12, 11)},
    {"text_str": "December twelve fifty six", "date_val": date(1956, 12, 12)},
    {"text_str": "February twelve nineteen sixty six", "date_val": date(1966, 2, 12)},
    {"text_str": "February twelve two thousand six", "date_val": date(2006, 2, 12)},
    {"text_str": "February twelve two thousand twelve", "date_val": date(2012, 2, 12)},
    {"text_str": "August thirty one two thousand one", "date_val": date(2001, 8, 31)},
    {"text_str": "August thirty one zero six", "date_val": date(2006, 8, 31)},
    {"text_str": "march fifteenth nineteen fifty four", "date_val": date(1954, 3, 15)},
    {"text_str": "march the fifteenth of nineteen fifty four", "date_val": date(1954, 3, 15)},
    {"text_str": "may the fourteenth nineteen forty nine", "date_val": date(1949, 5, 14)},
    {"text_str": "five fourteen nineteen forty nine", "date_val": date(1949, 5, 14)},
    {"text_str": "zero five one four one nine four nine", "date_val": date(1949, 5, 14)},
    {"text_str": "june sixteen nineteen sixty six", "date_val": date(1966, 6, 16)},
    {"text_str": "june sixteen nineteen six six", "date_val": date(1966, 6, 16)},
    {"text_str": "ten nineteen nineteen eighty four", "date_val": date(1984, 10, 19)},
    {"text_str": "ten nineteen nineteen eight four", "date_val": date(1984, 10, 19)},
    {"text_str": "july twenty fifth nineteen seventy", "date_val": date(1970, 7, 25)},
    {"text_str": "seven two five nineteen seventy", "date_val": date(1970, 7, 25)},
    {"text_str": "eight eight sixty", "date_val": date(1960, 8, 8)},
    {"text_str": "august the eighth nineteen sixty", "date_val": date(1960, 8, 8)},
    {"text_str": "two eight seventy five", "date_val": date(1975, 2, 8)},
    {"text_str": "september the twenty eighth nineteen seventy two", "date_val": date(1972, 9, 28)},
    {"text_str": "june six six six", "date_val": date(1966, 6, 6)},
    {"text_str": "six eight nineteen sixty seven", "date_val": date(1967, 6, 8)},
    {"text_str": "april twenty third nineteen seventy four", "date_val": date(1974, 4, 23)},
    {"text_str": "august fourteenth nineteen ninety three", "date_val": date(1993, 8, 14)},
    {"text_str": "two twenty forty three", "date_val": date(1943, 2, 20)},
    {"text_str": "june nineteenth two thousand seven", "date_val": date(2007, 6, 19)},
    {"text_str": "zero eight zero seven nineteen forty four", "date_val": date(1944, 8, 7)},
    {"text_str": "march third twenty twenty", "date_val": date(2020, 3, 3)},
    {"text_str": "november the fifteenth nineteen fifty four", "date_val": date(1954, 11, 15)},
    {"text_str": "august first nineteen fifty seven", "date_val": date(1957, 8, 1)},
    {"text_str": "ten nineteen nineteen", "date_val": date(2019, 10, 19)},
    {"text_str": "ten nineteen nineteen eighty four", "date_val": date(1984, 10, 19)},
    {"text_str": "six twenty two sixty six", "date_val": date(1966, 6, 22)},
    {"text_str": "april fifteenth nineteen forty four", "date_val": date(1944, 4, 15)},
    {"text_str": "eleven twelve forty eight", "date_val": date(1948, 11, 12)},
    {"text_str": "five fifteen sixty four", "date_val": date(1964, 5, 15)},
    {"text_str": "april nineteenth nineteen fifty one", "date_val": date(1951, 4, 19)},
    {"text_str": "nine five sixty one", "date_val": date(1961, 9, 5)},
    {"text_str": "two twelve nineteen sixty six", "date_val": date(1966, 2, 12)},
    {"text_str": "three twenty nine ninety five", "date_val": date(1995, 3, 29)},
    {"text_str": "two eight seventy five", "date_val": date(1975, 2, 8)},
    {"text_str": "may fourth nineteen fifty eight", "date_val": date(1958, 5, 4)},
    {"text_str": "september the twenty eighth nineteen seventy two", "date_val": date(1972, 9, 28)},
    {"text_str": "nine six fifty four", "date_val": date(1954, 9, 6)},
    {"text_str": "ten nineteen nineteen ninety three", "date_val": date(1993, 10, 19)},
    {"text_str": "six eight nineteen sixty seven", "date_val": date(1967, 6, 8)},
    {"text_str": "april twenty third nineteen seventy four", "date_val": date(1974, 4, 23)},
    {"text_str": "april twenty four two thousand eight", "date_val": date(2008, 4, 24)},
    {"text_str": "five twenty five forty two", "date_val": date(1942, 5, 25)},
    {"text_str": "january twenty first nineteen fifty one", "date_val": date(1951, 1, 21)},
    {"text_str": "five thirty nineteen forty eight", "date_val": date(1948, 5, 30)},
    {"text_str": "april sixteenth nineteen sixty", "date_val": date(1960, 4, 16)},
    {"text_str": "eleven twenty seven nineteen forty eight", "date_val": date(1948, 11, 27)},
    {"text_str": "november six nineteen forty one", "date_val": date(1941, 11, 6)},
    {"text_str": "ten twenty nine forty six", "date_val": date(1946, 10, 29)},
    {"text_str": "july seventeen nineteen eighty one", "date_val": date(1981, 7, 17)},
    {"text_str": "january fourteenth nineteen seventy five", "date_val": date(1975, 1, 14)},
    {"text_str": "january twenty third nineteen sixty six", "date_val": date(1966, 1, 23)},
    {"text_str": "march twelfth nineteen thirty four", "date_val": date(1934, 3, 12)},
    {"text_str": "december the first nineteen sixty six", "date_val": date(1966, 12, 1)},
    {"text_str": "november twenty seventh nineteen eighty six", "date_val": date(1986, 11, 27)},
    {"text_str": "four twenty one fifty six", "date_val": date(1956, 4, 21)},
    {"text_str": "february twenty fifth nineteen eighty one", "date_val": date(1981, 2, 25)},
    {"text_str": "eight eight two thousand and nine", "date_val": date(2009, 8, 8)},
    {"text_str": "may twenty fourth two thousand eight", "date_val": date(2008, 5, 24)},
    {"text_str": "september third two thousand ten", "date_val": date(2010, 9, 3)},
    {"text_str": "may twenty first two thousand nine", "date_val": date(2009, 5, 21)},
    {"text_str": "zero six nineteen twenty twenty three", "date_val": date(2023, 6, 19)},
    {"text_str": "zero one zero two twenty twenty three", "date_val": date(2023, 1, 2)},
    {"text_str": "nine sixteen forty eight", "date_val": date(1948, 9, 16)},
    {"text_str": "january twenty seventh nineteen forty nine", "date_val": date(1949, 1, 27)},
    {"text_str": "march twentieth nineteen seventy seven", "date_val": date(1977, 3, 20)},
    {"text_str": "may six nineteen ninety", "date_val": date(1990, 5, 6)},
    {"text_str": "ten seventeen nineteen seventy eight", "date_val": date(1978, 10, 17)},
    {"text_str": "october ten nineteen forty three", "date_val": date(1943, 10, 10)},
    {"text_str": "march twelfth nineteen fifty five", "date_val": date(1955, 3, 12)},
    {"text_str": "september the third nineteen ninety nine", "date_val": date(1999, 9, 3)},
    {"text_str": "september the third two thousand", "date_val": date(2000, 9, 3)},
    {"text_str": "september the third two thousand one", "date_val": date(2001, 9, 3)},
    {"text_str": "september the third two thousand three", "date_val": date(2003, 9, 3)},
    {"text_str": "september the third two thousand thirteen", "date_val": date(2013, 9, 3)},
    {"text_str": "september the third two thousand twenty", "date_val": date(2020, 9, 3)},
    {"text_str": "september the third twenty twenty", "date_val": date(2020, 9, 3)},
    {"text_str": "ten fifteen ninety six", "date_val": date(1996, 10, 15)},
    {"text_str": "twelve twenty two nineteen eighty", "date_val": date(1980, 12, 22)},
    {"text_str": "eleven thirty thirty nine", "date_val": date(1939, 11, 30)},
    {"text_str": "march twenty eighth nineteen forty one", "date_val": date(1941, 3, 28)},
    {"text_str": "february twenty fifth nineteen eighty one", "date_val": date(1981, 2, 25)},
    {"text_str": "four twenty one fifty six", "date_val": date(1956, 4, 21)},
    {"text_str": "november twenty seventh nineteen eighty six", "date_val": date(1986, 11, 27)},
    {"text_str": "december the first nineteen sixty six", "date_val": date(1966, 12, 1)},
    {"text_str": "august twenty six twenty eleven", "date_val": date(2011, 8, 26)},
    {"text_str": "zero six nineteen twenty twenty three", "date_val": date(2023, 6, 19)},
    {"text_str": "may twenty first two thousand nine", "date_val": date(2009, 5, 21)},
    {"text_str": "eight nine thirty four", "date_val": date(1934, 8, 9)},
    {"text_str": "six five fifty four", "date_val": date(1954, 6, 5)},
    {"text_str": "april twenty third two thousand and three", "date_val": date(2003, 4, 23)},
    {"text_str": "three twenty nine nineteen fifty four", "date_val": date(1954, 3, 29)},
    {"text_str": "three twelve fifty", "date_val": date(1950, 3, 12)},
    {"text_str": "three twelve one nine five zero", "date_val": date(1950, 3, 12)},
    {"text_str": "three twelve twenty", "date_val": date(2020, 3, 12)},
    {"text_str": "zero one zero five one nine five six", "date_val": date(1956, 1, 5)},
    {"text_str": "08081960", "date_val": date(1960, 8, 8)},
    {"text_str": "8860", "date_val": date(1960, 8, 8)},
    {"text_str": "five seventeen fifty four", "date_val": date(1954, 5, 17)},
    {"text_str": "three eighteen nine", "date_val": date(2009, 3, 18)},
    {"text_str": "1 0 nineteen fifty eight", "date_val": date(1958, 10, 19)},
    {"text_str": "0 1 3 1 1 9 6 1", "date_val": date(1961, 1, 31)},
    {"text_str": "october seventh nineteen seventy", "date_val": date(1970, 10, 7)},
    {"text_str": "september sixteenth nineteen forty two", "date_val": date(1942, 9, 16)},
    {"text_str": "august tenth nineteen fifty nine", "date_val": date(1959, 8, 10)},
    {"text_str": "0 5 2 4 1 9 4 9", "date_val": date(1949, 5, 24)},
    {"text_str": "0 8 1 1 1 9 5 9", "date_val": date(1959, 8, 11)},
    {"text_str": "five fifteen fifty eight", "date_val": date(1958, 5, 15)},
    # Should be able to get this one. The three and eighteen can only be understood as March 18.
    # So year of nine eighty three should be able to be parsed as nineteen eighty three.
    {"text_str": "three eighteen nine eighty three", "date_val": date(1983, 3, 18)},
    {"text_str": "010260", "date_val": date(1960, 1, 2)},
    {"text_str": "five seventeen fifty four", "date_val": date(1954, 5, 17)},
    {"text_str": "let me just go through and see what 1 1 1 7 1 9 4 4", "date_val": date(1944, 11, 17)},
    {"text_str": "hello november twenty five nineteen eighty five", "date_val": date(1985, 11, 25)},
    {"text_str": "one twelve twenty three", "date_val": date(2023, 1, 12)},
    {"text_str": "january twelfth two thousand twenty three", "date_val": date(2023, 1, 12)},
    {"text_str": "ten seven fifty seven", "date_val": date(1957, 10, 7)},
    {"text_str": "0 6 0 7 1 9 8 7 #", "date_val": date(1987, 6, 7)},
    {"text_str": "eight twenty one sixty nine", "date_val": date(1969, 8, 21)},
    {"text_str": "0 0 1 2 4 1 9 5 8", "date_val": date(1958, 1, 24)},
    {"text_str": "problem what's it called august thirteenth nineteen ninety one", "date_val": date(1991, 8, 13)},
    {"text_str": "eight nineteen forty one", "date_val": date(1941, 8, 19)},
    {"text_str": "february twenty fourth nineteen fifty", "date_val": date(1950, 2, 24)},
    {"text_str": "october the sixteen nineteen fifty eight", "date_val": date(1958, 10, 16)},
    {"text_str": "january twenty fourth nineteen fifty eight", "date_val": date(1958, 1, 24)},
    {"text_str": "january twenty first nineteen forty eight", "date_val": date(1948, 1, 21)},
    {"text_str": "december first nineteen fifty nine", "date_val": date(1959, 12, 1)},
    {"text_str": "december twenty six nineteen sixty seven", "date_val": date(1967, 12, 26)},
    {"text_str": "july seventh twenty fifteen", "date_val": date(2015, 7, 7)},
    {"text_str": "july eighth twenty fifteen", "date_val": date(2015, 7, 8)},
    {"text_str": "july eight twenty fifteen", "date_val": date(2015, 7, 8)},
    {"text_str": "september fifth nineteen forty nine", "date_val": date(1949, 9, 5)},
    {"text_str": "january twenty first nineteen seventy", "date_val": date(1970, 1, 21)},
    {"text_str": "october eighth nineteen thirty three", "date_val": date(1933, 10, 8)},
    {"text_str": "ten o eight thirty three", "date_val": date(1933, 10, 8)},
    {"text_str": "october eighteenth nineteen forty two", "date_val": date(1942, 10, 18)},
    {"text_str": "october eighteenth nineteen forty", "date_val": date(1940, 10, 18)},
    {"text_str": "three twelve fifty five", "date_val": date(1955, 3, 12)},
    {"text_str": "christy liberty three twelve fifty five", "date_val": date(1955, 3, 12)},
    {"text_str": "december ninth twenty nineteen", "date_val": date(2019, 12, 9)},
    {"text_str": "august twenty sixth two thousand and eleven", "date_val": date(2011, 8, 26)},
    {"text_str": "august twenty six twenty eleven", "date_val": date(2011, 8, 26)},
    {"text_str": "january nineteenth nineteen seventy", "date_val": date(1970, 1, 19)},
    {"text_str": "august seven nineteen sixty", "date_val": date(1960, 8, 7)},
    {"text_str": "february twenty eighth nineteen sixty eight", "date_val": date(1968, 2, 28)},
    {"text_str": "zero four one eight one three", "date_val": date(2013, 4, 18)},
    {"text_str": "october ninth nineteenth eighty four", "date_val": date(1984, 10, 9)},
    {"text_str": "january sixth twenty fifteen", "date_val": date(2015, 1, 6)},
    {"text_str": "january one twenty fifteen", "date_val": date(2015, 1, 1)},
    {"text_str": "one nine six five", "date_val": date(1965, 1, 9)},
    {"text_str": "june the second nineteen sixty five", "date_val": date(1965, 6, 2)},
    {"text_str": "six two sixty five", "date_val": date(1965, 6, 2)},
    {"text_str": "1 1 0 1 1 9 5 6", "date_val": date(1956, 11, 1)},
    {"text_str": "1 1 0 1 5 6", "date_val": date(1956, 11, 1)},
    {"text_str": "one one zero one one nine five six", "date_val": date(1956, 11, 1)},
    {"text_str": "eleven one nineteen fifty six", "date_val": date(1956, 11, 1)},
    {"text_str": "eleven one two thousand one", "date_val": date(2001, 11, 1)},
    {"text_str": "twelve thirteen two thousand and two", "date_val": date(2002, 12, 13)},
    {"text_str": "twelve thirteen two thousand and two", "date_val": date(2002, 12, 13)},
    {"text_str": "twelve thirteen two thousand two", "date_val": date(2002, 12, 13)},
    {"text_str": "twelve thirteen twenty oh two", "date_val": date(2002, 12, 13)},
    {"text_str": "twelve thirteen two zero zero two", "date_val": date(2002, 12, 13)},
    {"text_str": "twelve thirteen two thousand and twenty", "date_val": date(2020, 12, 13)},
    {"text_str": "twelve thirteen two thousand twenty", "date_val": date(2020, 12, 13)},
    {"text_str": "twelve thirteen twenty twenty", "date_val": date(2020, 12, 13)},
]


@pytest.mark.parametrize("item", date_text)
def test_correct_dob_date_conversion(item):
    rsl = parse_dob_candidates(item["text_str"])
    date_val = item["date_val"]
    try:
        date_obj = date(rsl["dob_candidates"][0]["year"], rsl["dob_candidates"][0]["month"], rsl["dob_candidates"][0]["day"])
    except Exception:
        date_obj = None
    assert date_obj == date_val, f"Parse date: {item['text_str']}, Expected: {date_val}, Got: {date_obj}"
