apiVersion: v1
kind: ConfigMap
metadata:
  name: healthtech-config
  labels:
    app: healthtech-api
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  DEMO_MODE: "false"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
